-- Auto-generated DB Seed File for crops_master_data
DELETE FROM crops_master_data;

INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'বোরো ধান', 'ব্রি ধান ২৮', 'হাওর বাদে দেশের সব অঞ্চল', 'উঁচু ও মাঝারি জমি', 24, 140, 'মাঝারি ব্লাস্ট প্রতিরোধক', 'আগাম জাত', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'বোরো ধান', 'ব্রি ধান ২৯', 'দেশের সব অঞ্চল', 'উঁচু ও মাঝারি জমি', 30, 160, 'রোগ বালাই প্রতিরোধী', 'উচ্চ ফলনশীল', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'বোরো ধান', 'ব্রি ধান ৮৯', 'দেশের সব অঞ্চল', 'উঁচু ও মাঝারি জমি', 32, 158, 'রোগ বালাই প্রতিরোধী', 'উচ্চ ফলনশীল', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'বোরো ধান', 'ব্রি ধান ৯২', 'দেশের সব অঞ্চল', 'উঁচু ও মাঝারি জমি', 33, 156, 'রোগ বালাই প্রতিরোধী', 'খরা সহনশীল', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'আমন ধান', 'ব্রি ধান ৮৭', 'রংপুর ও রাজশাহী অঞ্চল', 'মাঝারি নিচু জমি', 26, 127, 'রোগ বালাই প্রতিরোধী', 'আগাম জাত', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ধান', 'আউশ ধান', 'ব্রি ধান ৪৮', 'দেশের সব অঞ্চল', 'উঁচু জমি', 22, 110, 'রোগ বালাই প্রতিরোধী', 'উচ্চ ফলনশীল', 'BRRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'টমেটো', 'বারি টমেটো-১ (মানিক)', 'সব অঞ্চল', 'দোআঁশ', 120, 110, 'উইল্ট প্রতিরোধক', 'শীতকালীন উচ্চ ফলনশীল', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'টমেটো', 'বারি টমেটো-২ (রতন)', 'সব অঞ্চল', 'বেলে দোআঁশ', 130, 115, 'রোগ বালাই প্রতিরোধী', 'শীতকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'বেগুন', 'বারি বেগুন-৪ (কাজলা)', 'সব অঞ্চল', 'বেলে দোআঁশ', 110, 150, 'ঢলে পড়া রোগ প্রতিরোধী', 'শীতকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'বেগুন', 'বারি বিটি বেগুন-২', 'সব অঞ্চল', 'দোআঁশ', 130, 160, 'ডগা ও ফল ছিদ্রকারী পোকা প্রতিরোধী', 'বিটি জাত', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'ফুলকপি', 'বারি ফুলকপি-১ (রূপা)', 'সব অঞ্চল', 'দোআঁশ-এটেল', 80, 95, 'রোগ বালাই প্রতিরোধী', 'শীতকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'বাঁধাকপি', 'বারি বাঁধাকপি-১ (প্রভাতি)', 'সব অঞ্চল', 'দোআঁশ-এটেল', 100, 90, 'রোগ বালাই প্রতিরোধী', 'আগাম জাত', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('সবজি', 'শিম', 'বারি শিম-৬', 'সব অঞ্চল', 'দোআঁশ', 60, 140, 'ভাইরাস প্রতিরোধী', 'শীতকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('আঁশ', 'পাট', 'বিজেআরআই তোষা পাট-৮', 'দেশের বেশিরভাগ অঞ্চল', 'দোআঁশ', 15, 115, 'কান্ড পচা রোগ প্রতিরোধী', 'উচ্চ ফলনশীল', 'BJRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('আঁশ', 'পাট', 'বিজেআরআই দেশি পাট-৬', 'দেশের বেশিরভাগ অঞ্চল', 'দোআঁশ', 12, 110, 'রোগ বালাই প্রতিরোধী', 'সাদা পাট', 'BJRI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('কন্দাল', 'আলু', 'বারি আলু-৭ (ডায়মন্ট)', 'দেশের সব অঞ্চল', 'বেলে দোআঁশ', 110, 95, 'লেট ব্লাইট প্রতিরোধী', 'রপ্তানিযোগ্য', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('কন্দাল', 'আলু', 'বারি আলু-৮ (কার্ডিনাল)', 'সব অঞ্চল', 'বেলে দোআঁশ', 105, 90, 'রোগ বালাই প্রতিরোধী', 'লাল চামড়া', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ডাল', 'মসুর', 'বারি মসুর-৮', 'সব অঞ্চল', 'দোআঁশ', 8, 110, 'রাস্ট রোগ প্রতিরোধী', 'উচ্চ ফলনশীল', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ডাল', 'মুগ', 'বারি মুগ-৬', 'সব অঞ্চল', 'বেলে দোআঁশ', 6, 60, 'হলদে মোজাইক ভাইরাস প্রতিরোধী', 'গ্রীষ্মকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('তেল', 'সরিষা', 'বারি সরিষা-১৪', 'সব অঞ্চল', 'দোআঁশ', 6, 80, 'অল্টারনারিয়া ব্লাইট প্রতিরোধী', 'আগাম জাত', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('তেল', 'সরিষা', 'বারি সরিষা-১৭', 'সব অঞ্চল', 'দোআঁশ', 6.5, 85, 'রোগ বালাই প্রতিরোধী', 'উচ্চ ফলনশীল', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('গম', 'গম', 'বারি গম-৩৩', 'উত্তরাঞ্চল', 'দোআঁশ', 18, 110, 'ব্লাস্ট রোগ প্রতিরোধী', 'জিংক সমৃদ্ধ', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ভুট্টা', 'ভুট্টা', 'বারি হাইব্রিড ভুট্টা-৯', 'সব অঞ্চল', 'বেলে দোআঁশ', 40, 140, 'রোগ বালাই প্রতিরোধী', 'রবি মৌসুম', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('পেঁয়াজ', 'পেঁয়াজ', 'বারি পেঁয়াজ-১', 'সব অঞ্চল', 'বেলে দোআঁশ', 50, 120, 'রোগ বালাই প্রতিরোধী', 'শীতকালীন', 'BARI');
INSERT INTO crops_master_data (crop_category, crop_name, variety_name, suitable_regions, soil_type, base_yield_per_shotangsho_kg, avg_duration_days, disease_resistance, special_features, data_source) VALUES ('ফল', 'তরমুজ', 'পদ্মা', 'দক্ষিণাঞ্চল', 'বেলে দোআঁশ', 150, 90, 'রোগ বালাই প্রতিরোধী', 'গ্রীষ্মকালীন', 'BADC');
